config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'id/keywords/category/:slug', to: 'keywords#category'

  get 'id/keywords/subcategory/:slug', to: 'keywords#subcategory'

  get 'id/keywords/keyword/:slug', to: 'keywords#show'

  get 'id/:resource_type/:slug', to: 'resources#show', as: :resource

  post '/get_label', to: 'labels#find'
  post '/edit_label', to: 'labels#edit'

  get '/get_connections_for_chart', to: 'connections#distribution'
  get '/get_connections_for_graph', to: 'connections#visualise_person'
  get '/get_organisation_graph', to: 'connections#visualise_organisation'
  post '/get_connections', to: 'connections#find'
  post '/generate_connections', to: 'connections#generate'

  get '/uploads', to: 'uploads#index', as: :uploads
  get '/authorize_dropbox', to: 'uploads#authorize', as: :authorize_dropbox
  get '/dropbox_callback', to: 'uploads#dropbox_callback', as: :dropbox_callback
  post '/create_client_and_fetch_file', to: 'uploads#create_client_and_fetch_file', as: :fetch_file
  post '/process_data', to: 'uploads#process_data', as: :process_data

  get '/collection_tagging', to: 'collections#show', as: :collection_tagging

  post '/organisations/update', to: 'organisations#update', as: :update_organisation

  post '/people/update', to: 'people#update', as: :update_person

  post '/search', to: 'search#show', as: :search

  post '/sna_person_list', to: 'exports#person_export_csv', as: :person_export
  post '/sna_person_matrix', to: 'exports#person_matrix_csv', as: :person_matrix
  post '/person_dump', to: 'exports#person_dump_csv', as: :person_dump

  get '/about' => 'static#about', as: :about
  get '/contact' => 'static#contact', as: :contact
  get '/home' => 'static#home', as: :home

  devise_scope :user do
    root to: 'static#home', as: :logged_in_root
  end

  root to: 'devise/sessions#new'

end

app/models/organisation.rb
require 'memoist'
class Organisation < ResourceWithPresenter

  include Tripod::Resource
  extend TripodOverrides
  extend Memoist

  rdf_type 'http://www.w3.org/ns/org#Organization'
  graph_uri 'http://data.artsapi.com/graph/organisations'

  field :label, RDF::RDFS.label
  field :has_members, RDF::ORG['hasMember'], is_uri: true, multivalued: true
  field :linked_to, RDF::ORG['linkedTo'], is_uri: true, multivalued: true
  field :owns_domain, RDF::ARTS['ownsDomain'], is_uri: true
  field :works_on, RDF::ARTS['worksOn'], is_uri: true, multivalued: true

  field :graph_visualisation, RDF::ARTS['visualisation']

  # sic uri or extension
  field :sector, RDF::ARTS['sector'], is_uri: true

  # for location
  field :country, RDF::ARTS['locationCountry']
  field :city, RDF::ARTS['locationCity']

  # for heuristics
  field :common_subject_areas, RDF::ARTS['commonSubjectArea'], is_uri: true, multivalued: true
  field :common_keywords, RDF::ARTS['commonKeyword'], is_uri: true, multivalued: true

  def get_visualisation_graph
    if !self.graph_visualisation.nil?
      # expensive, not sure we want to do this
      set_visualisation_graph_async if Rails.env.production?
      JSON.parse(sanitize_json(self.graph_visualisation))
    else
      graph_json = D3::OrganisationsGraph.new(self).formatted_hash
      set_visualisation_graph(graph_json)
      graph_json
    end
  end

  def set_visualisation_graph(hash)
    self.graph_visualisation = hash.to_json
    self.save
  end

  def set_visualisation_graph_async
    current_user_id = User.current_user.id.to_s
    job_id = ::OrganisationsWorker.perform_in(10.seconds, self.uri.to_s, current_user_id)

    User.add_job_for_current_user(job_id)

    job_id
  end

  def sector_label
    SICConcept.find_class_or_subclass(self.sector).label rescue nil
  end

  def location_string
    "City: #{self.city || "Not known"}, Country: #{self.country || "Not known"}"
  end

  def get_top_subject_areas
    members = self.has_members.map { |uri| Person.find(uri) }

    areas = members.map(&:get_or_generate_subject_area!).flatten

    counter = {}

    areas.each do |subject_area|
      if counter.has_key?(subject_area)
        counter[subject_area] += 1
      else
        counter[subject_area] = 1
      end
    end

    counter.sort { |a, b| b[1] <=> a[1] }[0..2]
  end

  def get_common_subject_areas!
    common_subjects = get_top_subject_areas.map { |subj| subj[0] }.compact

    self.common_subject_areas = common_subjects
    self.save

    common_subjects
  end

  def get_top_keywords
    members = self.has_members.map { |uri| Person.find(uri) }

    keyword_lists = members.map(&:sorted_keywords)

    counter = {}

    keyword_lists.each do |list|
      list.each do |keyword_entry|
        if counter.has_key?(keyword_entry[0])
          counter[keyword_entry[0]] += keyword_entry[1]
        else
          counter[keyword_entry[0]] = keyword_entry[1]
        end
      end
    end

    counter.sort { |a, b| b[1] <=> a[1] }[0..9]
  end

  def get_common_keywords!
    top_ten_common_words = get_top_keywords.map { |kw| Keyword.uri_from_label(kw[0]) }

    self.common_keywords = top_ten_common_words
    self.save

    top_ten_common_words
  end

  def sanitize_json(string)
    string.strip
      .gsub(/(?:\\n)/, '')
      .gsub(/(?:\\r)/, '')
      .gsub(/\r/, '')
      .gsub(/\n/, '')
      .gsub(/\\n/, '')
      .gsub(/\\/, '')
  end

  # (re)generate connections for all members of an organisation
  def generate_all_connections!
    organisation_level_connections = []

    self.has_members.each do |member_uri|
      member = Person.find(member_uri)
      organisation_level_connections << member.get_connections!
    end

    organisation_level_connections.flatten
  end

  def generate_connections_async!
    job_ids = []

    self.has_members.each do |member_uri|
      member = Person.find(member_uri)
      job_ids << member.generate_connections_async
    end

    job_ids
  end

  def generate_visualisations_async!
    job_ids = []

    self.has_members.each do |member_uri|
      member = Person.find(member_uri)
      job_ids << member.set_visualisation_graph_async
    end

    job_ids << self.set_visualisation_graph_async

    job_ids
  end

  def force_regenerate_email_counts!
    self.has_members.each do |member_uri|
      p = Person.find(member_uri)
      p.number_of_incoming_emails(true)
      p.number_of_sent_emails(true)
    end
  end

  def members_with_more_than_x_connections(x)
    self.has_members.map { |m| m if Person.find(m).connections.length > x }.compact
  end
  # memoize :members_with_more_than_x_connections

  # look at extension and take a punt
  def best_guess_at_country
    return self.country if !self.country.nil?

    extension_possibilities = []
    extension_possibilities << ".#{self.uri.to_s.gsub(/^.+organisations\/.+\-/, '')}"
    extension_possibilities << self.uri.to_s.gsub(/^.+organisations\/[A-z]+/, '').gsub(/\-/, '.')
    extension_possibilities << self.uri.to_s.match(/\-[A-z]+\-[A-z]+$/)[0].gsub(/\-/, '.') rescue ''
    mapping = ArtsAPI::COUNTRIES_MAPPING

    result = nil
    extension_possibilities.each { |ex| result = mapping[ex] if mapping.has_key?(ex) }

    if !result.nil?
      self.country = result
      self.save
    end

    result
  end

  class << self

    def find_by_label(string)
      uri = User.current_user.within {
        Tripod::SparqlClient::Query.select("
          SELECT DISTINCT ?uri
          WHERE {
            GRAPH <http://data.artsapi.com/graph/organisations> {
              ?uri <http://www.w3.org/2000/01/rdf-schema#label> \"#{string}\" .
            }
          }
          LIMIT 1
        ")[0]["uri"]["value"]
      }

      Organisation.find(uri)
    end


    # all unhydrated orgs
    def total_count
    end

    # get all the strings that have been input for cities
    def all_unique_city_values
      sparql = "
      SELECT DISTINCT ?city
      WHERE 
      {
        GRAPH <http://data.artsapi.com/graph/organisations> {
          ?org <http://data.artsapi.com/def/arts/locationCity> ?city .
        }
      }"

      results = User.current_user.within { Tripod::SparqlClient::Query.select(sparql) }

      results.map { |r| r["city"]["value"] }
    end

    # get all orgs in a country and return their uri and label
    def all_organisations_in_country(country)
      sparql = "
      SELECT DISTINCT ?uri ?label
      WHERE 
      {
        VALUES ?country { \"#{country}\" }
        GRAPH <http://data.artsapi.com/graph/organisations> {
          ?uri <http://data.artsapi.com/def/arts/locationCountry> ?country .
          ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        }
      }
      "

      results = User.current_user.within { Tripod::SparqlClient::Query.select(sparql) }

      results.map { |r| [r["uri"]["value"], r["label"]["value"]] }
    end

    # get all orgs in a city and return their uri and label
    def all_organisations_in_city(city)
      sparql = "
      SELECT DISTINCT ?uri ?label
      WHERE 
      {
        VALUES ?city { \"#{city}\" }
        GRAPH <http://data.artsapi.com/graph/organisations> {
          ?uri <http://data.artsapi.com/def/arts/locationCity> ?city .
          ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        }
      }
      "

      results = User.current_user.within { Tripod::SparqlClient::Query.select(sparql) }

      results.map { |r| [r["uri"]["value"], r["label"]["value"]] }
    end

    # get all orgs in a sector and return their uri and label
    # expects a uri as input
    def all_organisations_in_sector(sector)
      sparql = "
      SELECT DISTINCT ?uri ?label
      WHERE 
      {
        VALUES ?sector { <#{sector}> }
        GRAPH <http://data.artsapi.com/graph/organisations> {
          ?uri <http://data.artsapi.com/def/arts/sector> ?sector .
          ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        }
      }
      "

      results = User.current_user.within { Tripod::SparqlClient::Query.select(sparql) }

      results.map { |r| [r["uri"]["value"], r["label"]["value"]] }
    end

    # takes a uri object or string
    def write_link(org_one, org_two)
      org_one = Organisation.find(org_one)
      org_two = Organisation.find(org_two)

      if org_one != org_two
        org_one.linked_to = org_one.linked_to + [org_two.uri] # write org:linkedTo
        org_two.linked_to = org_two.linked_to + [org_one.uri] # write org:linkedTo

        begin
          org_one.save!
          org_two.save!
        rescue
          false
        end
      end
    end

    # from a form
    def bootstrap_connections_and_vis_for(uri)
      organisation = Organisation.find(uri)

      job_ids = []
      job_ids << organisation.generate_connections_async!
      job_ids << organisation.generate_visualisations_async!

      job_ids
    end

    # for when you absolutely, positively need to process every dataset in the room
    # bear in mind that async-ness might cause problems in the end anyway
    def bootstrap_all!
      User.bootstrap_sic_for_current_user!
      User.bootstrap_keywords_for_current_user!

      organisations = Organisation.all.resources

      job_ids = []

      organisations.each do |org|
        job_ids << bootstrap_connections_and_vis_for(org.uri)
      end

      job_ids
    end

    # first, try and extract the owning org from current signed in user, else
    # a more pragmatic version; the Org with the largest number of links
    # will almost certainly be the owner organisation, and running through
    # only their members will save a ton of processing
    def bootstrap_owner_or_largest_org!
      begin
        User.bootstrap_sic_for_current_user!
        User.bootstrap_keywords_for_current_user!

        Rails.logger.debug "> [Bootstrap] Triggered by #{User.current_user.email}"

        owner_org = User.current_user.find_org_from_self_in_data

        owner_org.generate_connections_async!

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  before_filter :authenticate_user!

  def update

    respond_to do |format|
      format.js do

        begin
          org = Organisation.find(params[:uri])

          org.label = params[:label] if !params[:label].blank? && !params[:label].nil?
          org.country = params[:country] if !params[:country].blank? && !params[:country].nil?
          org.city = params[:city].strip.downcase.titleize if !params[:city].blank? && !params[:city].nil?
          org.sector = sic_label_to_uri_mapping[params[:sector]] if !params[:sector].blank? && !params[:sector].nil?

          org.save

          render nothing: true, status: 200
        rescue
          render nothing: true, status: 500
        end

      end
    end

  end

  private

  # we know labels are unique
  def sic_label_to_uri_mapping
    resources = SICConcept.all_classes_and_subclasses
    mapping = {}

    # array needs to be [label, value]
    resources.each do |resource|
      uri = resource.uri.to_s
      mapping[resource.label] = uri
    end

    mapping
  end

end

app/views/organisation/_analysis.html.erb
<div class='row no-margins'>
  <div class='col-md-6 col-md-offset-3'>
    <p class='lead text-center margin-top-50'>This panel shows information gleaned from the data using keyword analysis and SNA measures. More detailed information on each is below.</p>

    <!-- First section: subject area stuff from keywords -->
    <h3 class='margin-top-50'>Keyword Analysis</h3>

    <h4 class='margin-top-30'>Subject Area</h4>

    <p>The most common subject areas for members of this organisation are <strong><%= @presenter.common_subject_areas_sentence %></strong>.</p>
    <hr>

    <h4>Keywords</h4>
    <p>The most common keywords for members of this organisation are <strong><%= @presenter.common_keywords_sentence %></strong>.</p>
    <hr>

    <!-- Second section: Location and Sector  -->
    <h3>Location and Sector Export</h3>
    <p>Provided you have tagged the location and sector of organisations in the system, we can give some high-level information about your connections.</p>

    <p>To export this information in a tabular format, click the button below. Please make sure you have linked your Dropbox first. If you have not, <%= link_to 'click here to do so', uploads_path, target: '_blank' %>.</p>

    <div class='export-button margin-top-20'>
      <%= button_to "Export Sector and Location Data &rarr;".html_safe, person_export_path, remote: true, data: { disable_with: "Queuing Export...", confirm: "Are you sure all data processing has finished?" }, class: 'btn btn-info' %>
    </div>

    <hr>

    <!-- Third section: SNA stuff here  -->
    <h3>SNA Analysis and Matrix Export</h3>
    <p>Although this is no replacement for a full SNA study, some things can be calculated about your network from just the data available to ArtsAPI.</p>

    <p>The network density for the complete organisational network in this database is <strong><%= @presenter.network_density %></strong></p>

    <p>You can export a symmetric matrix of connectivity representing all people in the database that have sent or received email. Depending on its size, this may be used for further analysis or to import into specialist SNA software. Click the button below to generate this, but make sure you have linked your Dropbox first. If you have not, <%= link_to 'click here to do so', uploads_path, target: '_blank' %>.</p>

    <div class='export-button margin-top-20'>
      <%= button_to "Export Connectivity Matrix &rarr;".html_safe, person_matrix_path, remote: true, data: { disable_with: "Queuing Export...", confirm: "Are you sure all data processing has finished?" }, class: 'btn btn-info' %>
    </div>
    <hr>

    <!-- Fourth section: export -->
    <h3>Person Contact List Export</h3>

    <p>Click the button below to dump all Person resources, along with their key associated fields and fields from related resources (for example, their parent Organisation). Please make sure you have linked your Dropbox first. If you have not, <%= link_to 'click here to do so', uploads_path, target: '_blank' %>.</p>

    <div class='export-button margin-top-20'>
      <%= button_to "Export all Person Resources &rarr;".html_safe, person_dump_path, remote: true, data: { disable_with: "Queuing Export...", confirm: "Are you sure all data processing has finished?" }, class: 'btn btn-info' %>
    </div>
  </div>
</div>

<script type="text/javascript">

  $('.export-button form.button_to').bind('ajax:success', function() {
    alert('Exporting to Dropbox has been queued.');
  });

  $('.export-button form.button_to').bind('ajax:error', function() {
    alert('Something went wrong with your export - please make sure you have linked your Dropbox account on the data uploads page and try again.');
  });

</script>

app/views/organisation/_clustering.html.erb
<div class='row no-margins'>
  <div class='col-md-8 col-md-offset-2 margin-top-50'>

    <div class='clustering-country'>
      <h3>Linked Organisations by Country</h3>
      <table class='table table-striped'>
        <thead>
          <th>Country or Domain</th>
          <th>Number of Organisations</th>
        </thead>
        <tbody>
          <% @presenter.country_table.each do |row| %>
            <tr>
              <td>
                <a href="/collection_tagging?country=<%= Rails.env.test? ? row[0].gsub(/ /, '%20') : row[0] %>">
                  <%= row[0] %>
                </a>
              </td>
              <td>
                <%= row[1] %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class='clustering-city'>
      <hr>
      <h3 class='margin-top-50'>Linked Organisations by City</h3>
      <table class='table table-striped'>
        <thead>
          <th>City</th>
          <th>Number of Organisations</th>
        </thead>
        <tbody>
          <% @presenter.city_table.each do |row| %>
            <tr>
              <td>
                <a href="/collection_tagging?city=<%= Rails.env.test? ? row[0].gsub(/ /, '%20') : row[0] %>">
                  <%= row[0] %>
                </a>
              </td>
              <td>
                <%= row[1] %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class='clustering-sector'>
      <hr>
      <h3 class='margin-top-50'>Linked Organisations by Sector</h3>
      <table class='table table-striped'>
        <thead>
          <th>Sector</th>
          <th>Number of Organisations</th>
        </thead>
        <tbody>
          <% @presenter.sector_table.each do |row| %>
            <tr>
              <td>
                <a href="/collection_tagging?sector=<%= row[0] %>">
                  <%= row[1] %>
                </a>
              </td>
              <td>
                <%= row[2] %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/organisation/_graph.html.erb
<p id='organisation-graph-for' class='lead text-center' data-uri-for-graph='<%= @presenter.resource_uri %>'>
  Visual representation of organisational links for <span class='resource-label'><%= @presenter.title %></span class='resource-label'>
</p>
<!-- <p class='small' id='graph-legend'>
  This graph shows all organisational links and the members of those organisations. Where connections exist between people in the graph, they are shown as bold edges. The connection to the organisation they are a member of is expressed as a light edge. Due to the size of the data, this visualisation may take some time to settle into a stable shape, and is best viewed in a modern browser.
  <br>
  NB: A great deal of data is trimmed to make this possible to show on a normal-sized monitor and web browser - thus sometimes the weight of a node (connections) will be greater than the number of visible links, if some of the connections were with nodes that are not visualised as part of this graph.
</p> -->

<div id='graph-vis'>
  <div id='graph-loading-placeholder'>
    </p><em>Loading, please be patient...</em></p>
    <%= image_tag 'loading.gif', width: 60, height: 60 %>
  </div>
</div>

app/views/organisation/_links.html.erb
<div class='margin-top-50'>
  <p class='lead text-center'>
    Below is a list of all the Organisations that this Organisation is linked to. To bulk-edit these, <%= link_to 'click here', collection_tagging_path(organisation: @presenter.resource_uri), target: '_blank' %>.
  </p>
</div>

<table class='table table-striped margin-top-50'>
  <thead>
    <th>Organisation</th>
    <th>Members</th>
    <th>Links</th>
  </thead>
  <tbody>
    <% @presenter.linked_organisations_data.each do |org| %>

      <tr>
        <td>
          <span class='links-inline-edit-container'>
            <%= link_with_path_from org[0], text: org[3] %>
            <%= inline_edit_link_for("#{org[0]}") %>
          </span>
        </td>
        <td><%= org[1] %></td>
        <td><%= org[2] %></td>
      </tr>

    <% end %>
  </tbody>
</table>

app/views/organisation/_members.html.erb
<table class='table table-striped'>
  <thead>
    <th>Member</th>
    <th>Degree Centrality</th>
    <th>Number of known Connections</th>
  </thead>
  <tbody>
    <% @presenter.members_data.each do |member| %>
      <tr>
        <td>
          <span class='member-inline-edit-container'>
            <a href="<%= member[0] %>">
              <span class='ajax-label' data-uri="<%= member[1] %>">
                <%= member[1] %>
              </span>
            </a>
            <%= inline_edit_link_for("#{ArtsAPI::HOST}#{member[0]}") %>
          </span>
        </td>
        <td><%= member[2] %></td>
        <td><%= member[3] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organisation/_summary.html.erb
<div id='organisation-summary'>
  <blockquote>
    <ul class="list-inline">
      <li><p><%= @presenter.number_of_members %> Members</p></li>
      <li><p><%= @presenter.linked_organisations_text %></p></li>
      <li><p>Network Density: <%= @presenter.network_density.round(5) %></p></li>
    </ul>
  </blockquote>
</div>

app/views/organisation/_tabbed_table.html.erb
<div>
  <ul class="nav nav-tabs nav-justified" role="tablist" id='resource-tabs'>
    <li role="presentation" class="active">
      <a href="#graph" aria-controls="graph" role="tab" data-toggle="tab">Graph</a>
    </li>
    <li role="presentation">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#clustering" aria-controls="clustering" role="tab" data-toggle="tab">Clustering</a>
    </li>
    <li role="presentation">
      <a href="#members" class='trigger-label-load' aria-controls="members" role="tab" data-toggle="tab">Members</a>
    </li>
    <li role="presentation">
      <a href="#links" aria-controls="links" role="tab" data-toggle="tab">Links</a>
    </li>
    <li role="presentation">
      <a href="#data" aria-controls="data" role="tab" data-toggle="tab">Data</a>
    </li>
  </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="graph">
        <%= render 'organisation/graph' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="analysis">
        <%= render 'organisation/analysis' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="clustering">
        <%= render 'organisation/clustering' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="members">
        <%= render 'organisation/members' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="links">
        <%= render 'organisation/links' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="data">
        <%= render 'shared/data' %>
      </div>
    </div>
  </div>
</div>