config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'id/keywords/category/:slug', to: 'keywords#category'

  get 'id/keywords/subcategory/:slug', to: 'keywords#subcategory'

  get 'id/keywords/keyword/:slug', to: 'keywords#show'

  get 'id/:resource_type/:slug', to: 'resources#show', as: :resource

  post '/get_label', to: 'labels#find'
  post '/edit_label', to: 'labels#edit'

  get '/get_connections_for_chart', to: 'connections#distribution'
  get '/get_connections_for_graph', to: 'connections#visualise_person'
  get '/get_organisation_graph', to: 'connections#visualise_organisation'
  post '/get_connections', to: 'connections#find'
  post '/generate_connections', to: 'connections#generate'

  get '/uploads', to: 'uploads#index', as: :uploads
  get '/authorize_dropbox', to: 'uploads#authorize', as: :authorize_dropbox
  get '/dropbox_callback', to: 'uploads#dropbox_callback', as: :dropbox_callback
  post '/create_client_and_fetch_file', to: 'uploads#create_client_and_fetch_file', as: :fetch_file
  post '/process_data', to: 'uploads#process_data', as: :process_data

  get '/collection_tagging', to: 'collections#show', as: :collection_tagging

  post '/organisations/update', to: 'organisations#update', as: :update_organisation

  post '/people/update', to: 'people#update', as: :update_person

  post '/search', to: 'search#show', as: :search

  post '/sna_person_list', to: 'exports#person_export_csv', as: :person_export
  post '/sna_person_matrix', to: 'exports#person_matrix_csv', as: :person_matrix
  post '/person_dump', to: 'exports#person_dump_csv', as: :person_dump

  get '/about' => 'static#about', as: :about
  get '/contact' => 'static#contact', as: :contact
  get '/home' => 'static#home', as: :home

  devise_scope :user do
    root to: 'static#home', as: :logged_in_root
  end

  root to: 'devise/sessions#new'

end

app/controllers/uploads_controller.rb
require 'dropbox_sdk'

class UploadsController < ApplicationController

  before_filter :authenticate_user!

  # this controller is effectively a wizard-like flow for authing with Dropbox.

  # step 1: the user will be sent to dropbox to auth
  def index
  end

  # step 2: create session and auth
  def authorize
    db_session = UploadClient.create_dropbox_session
    session[:dropbox_session] = db_session.serialize

    redirect_to db_session.get_authorize_url url_for(:action => 'dropbox_callback')
  end

  # step 2: we are redirected here after auth
  def dropbox_callback
    db_session = DropboxSession.deserialize(session[:dropbox_session])

    unless params[:not_approved] == 'true'
      # get an oauth access token
      access_token = db_session.get_access_token
      UploadClient.save_current_user_auth_code!(access_token)

      flash[:success] = "You have successfully authorized your Dropbox."
    else
      flash[:danger] = "You have to authorize to continue."
    end

    redirect_to uploads_path
  end

  # NB: we skip step 1 & 2 if the current_user already has
  # a dropbox_auth_token field populated
  # step 3: create a dropbox client using the auth code
  # then fetch the file from the location passed in params
  def create_client_and_fetch_file
    file_location_string = params[:location].chomp
    mine_keywords = !!(params[:mine_keywords])

    begin

      upload_file_async(file_location_string, mine_keywords)

      flash[:success] = "Upload of file '#{file_location_string}' queued."

      render nothing: true, status: 200
    rescue Exception => e

      Rails.logger.debug "Error: #{e.class.to_s} #{e.message}\n\nStack:\n"
      e.backtrace.map { |line| Rails.logger.debug(line) }

      flash[:danger] = "Upload of file '#{file_location_string}' failed, please try again"

      render nothing: true, status: 500
    end
  end

  # this method should be triggered by the user 
  # once they've uploaded all their data
  # I feel pretty sorry for Fuseki, this will be big
  def process_data
    # do we want to force generation of everything?
    force_all = params[:force] if params.has_key?(:force)

    # lock it for a day
    current_user.last_clicked_process_data_button = DateTime.now
    current_user.save

    begin
      job_ids = force_all ? Organisation.bootstrap_all! : Organisation.bootstrap_owner_or_largest_org!

      flash[:success] = "Success! #{job_ids.count} data tasks scheduled."
      render nothing: true, status: 202
    rescue
      flash[:danger] = "There was an error, please try scheduling later."
      render nothing: true, status: 500
    end

  end

  private

  def upload_file_async(file_location_string, mine_keywords)
    current_user_id = User.current_user.id.to_s
    job_id = ::UploadsWorker.perform_in(10.seconds, 'true', current_user_id, file_location_string, mine_keywords)

    User.add_job_for_current_user(job_id)

    job_id
  end

end

app/views/uploads/_authorization_form.html.erb
<div class='row no-margin'>
  <div class='col-md-7'>
    <p class='text-justify'>
      In order to provide a consistent experience for uploading and working with large files, we use Dropbox to import data from and export data to a linked Dropbox account that you own.
    </p>
    <p class='text-justify'>
      If you have not yet, you will need to upload your email dumps (in mbox format) to the Dropbox account that you link to ArtsAPI.
    </p>
    <p class='text-justify'>
      Only files that you select will be imported into ArtsAPI, and once they have been processed you may delete them from your Dropbox.
    </p>
    <p class='text-justify'>
      You are seeing this page because you have not yet linked your Dropbox account, please click on the button to do so.
    </p>
  </div>
  <div class='col-md-1'>
  </div>
  <div class='col-md-4'>
    <%= link_to image_tag("upload_white.png", width: 40, height: 40, class: 'margin-bottom-5') + ' Authorize Dropbox', authorize_dropbox_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

app/views/uploads/_file_location_form.html.erb
<p>
  Please provide the path to the file you wish to upload. This should be relative to the root of your Dropbox folder. 
</p>
<p>
  e.g. For a file named <strong>'your-file-name.mbox'</strong>, in the folder <strong>'artsapi-uploads'</strong> located at the root of your dropbox, the location will be: <strong>'/artsapi-uploads/your-file-name.mbox'</strong>. 
</p>
<p>
  Note that ArtsAPI expects files in the <a href="https://en.wikipedia.org/wiki/Mbox" target='_blank'>mbox</a> format, so your file should have an .mbox extension, or be called <strong>mbox</strong> within a containing folder, i.e. <strong>'/containing-folder/mbox'</strong>. Different email clients will export to mbox in different ways, so make sure your upload follows one of these two patterns.
</p>

<hr>

<%= form_tag('/create_client_and_fetch_file', method: :post, class: 'width-50 file-location-form', remote: true) do %>

  <div class="form-group">
    <%= label_tag :location, 'File location:' %>
    <%= text_field_tag :location, '', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= check_box_tag :mine_keywords, 1, true %>
    <%= label_tag :mine_keywords, 'Mine keywords from email contents (Recommended)?' %>
  </div>

  <%= submit_tag 'Upload', class: 'btn btn-lg btn-primary', data: { disable_with: "Upload scheduled" } %>

<% end %>

<p class='margin-top-10'>
  <%= link_to "&larr; Return home while upload completes".html_safe, root_path %>
</p>

<script type="text/javascript">
  $('.file-location-form').bind('ajax:success', function() {
    alert('Upload successfully queued.');
  });
</script>

app/views/uploads/_process_data_form.html.erb
<hr>
<h4>Complete Upload and Process Data</h4>
<p>
  <em>Finished uploading <strong>all</strong> of your data? Then it's time to run the initial analysis. Please note, this will take some time, so you may want to leave it running over a lunch break or overnight.</em>
</p>
<%= button_to 'Process uploaded data', process_data_path, remote: true, data: { disable_with: "Processing...", confirm: "Are you sure all data imports have finished?" }, class: 'btn btn-lg btn-success' %>

app/views/uploads/index.html.erb
<div class='row no-margins'>
  <div class='col-md-8 col-md-offset-2'>
    <h3>Upload Data to ArtsAPI</h3>

    <% if UploadClient.current_user_has_auth_code? %>
      <%= render 'file_location_form' %>
      <%# render 'process_data_form' %>
    <% else %>
      <%= render 'authorization_form' %>
    <% end %>
  </div>
</div>